apiVersion: v1
kind: Service
metadata:
  name: discoodle-backend # Sets service name
  labels:
    app: discoodle-backend # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 8080
      name: http
  selector:
    app: springboot
