apiVersion: v1
kind: Service
metadata:
  namespace: discoodle-transverse
  name: mariadb # Sets service name
  labels:
    app: mariadb # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 3306 # Sets port to run the postgres application
      name: db
  selector:
    app: database
