kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: discoodle-transverse
  name: discoodle-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  namespace: discoodle-transverse
  name: mariadb-data-claim # Sets name of PV
spec:
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size
