apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yml
- frontend/frontend-deployment.yml
- frontend/frontend-service.yml
- frontend/frontend-config.yml
- backend/backend-deployment.yml
- backend/backend-service.yml