apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sandbox-discoodle

configMapGenerator:
  - name: backend-config
    envs:
      - application.env

patches:
  - target:
      kind: Ingress
      name: discoodle-ingress
    path: ./patches/ingress.yml

