
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: discoodle

configMapGenerator:
  - name: backend-config
    envs:
      - application.env

patches:
  - target:
      kind: Ingress
      name: ptf-ingress
    path: ./patches/ingress.yml
