apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    include /etc/nginx/modules-enabled/*.conf;

    events
    {
        worker_connections 768;
        # multi_accept on;
    }

    http
    {
        client_max_body_size 1500M;

        upstream discoodle-backend
        {
            server discoodle-backend:8080  max_conns=10;
        }

        server
        {
            listen 80;
            listen [::]:80;
            server_name     localhost;

            client_max_body_size 1500M;

            root /usr/share/nginx/html;

            index  index.html index.htm;
            include /etc/nginx/mime.types;
            default_type  application/octet-stream;

            server_tokens       off;
            keepalive_timeout   75;

            add_header  Strict-Transport-Security "max-age=31536000; includeSubDomains; always";
            add_header  X-Content-Type-Options nosniff;
            add_header  X-Frame-Options "SAMEORIGIN";
            add_header  X-XSS-Protection "1; mode=block";
            add_header  Referrer-Policy strict-origin-when-cross-origin;

            # Deny access on forbidden extensions
            location ~ \.(ht|sql|bat|git|ini|sh|svn[^.]*|tpl)$ {
                deny all;
            }

            location / {
                try_files $uri $uri/ /index.html;
            }
        }

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
    }
