apiVersion: v1
kind: Service
metadata:
  name: discoodle-frontend # Sets service name
  labels:
    app: discoodle-frontend # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 80
      name: http
  selector:
    app: nginx
